begin;
set local search_path = public, extensions;

select plan(42);

select has_table('public', 'championship_tiebreakers', 'championship state is persisted');
select has_table('public', 'championship_participants', 'all tied leaders are persisted');
select has_table('public', 'championship_submissions', 'championship submissions are persisted');
select has_table('private', 'championship_specs', 'championship seeds and expected results are private');
select has_table('public', 'match_results', 'authoritative match results are persisted');
select has_table('public', 'match_result_players', 'final ranking rows are persisted');
select has_table('public', 'match_stat_awards', 'derived match awards are persisted');
select has_table('public', 'rematches', 'completed matches map to a new rematch identity');
select has_column('public', 'championship_tiebreakers', 'submission_deadline', 'championship deadline is server-owned');
select has_column('public', 'championship_tiebreakers', 'resolution_method', 'championship outcome method is auditable');
select has_column('public', 'championship_submissions', 'normalized_distance', 'server-derived distance is persisted');
select has_column('public', 'championship_submissions', 'elapsed_ms', 'validated timing is persisted');
select has_column('public', 'match_results', 'completed_at', 'authoritative completion timestamp is persisted');
select has_column('public', 'match_result_players', 'final_rank', 'competition rank is persisted');
select has_column('public', 'match_result_players', 'display_order', 'deterministic display order is separate from rank');
select has_column('public', 'match_stat_awards', 'category', 'award category is typed');
select col_is_pk('public', 'match_results', 'room_id', 'one final result exists per match identity');
select col_is_fk('public', 'match_results', array['room_id','winner_player_id'], 'winner must belong to the result room');
select col_is_fk('public', 'championship_participants', array['room_id','player_id'], 'finalists must belong to the championship room');
select col_is_fk('public', 'championship_submissions', array['room_id','player_id'], 'only finalists can own submissions');
select has_index('public', 'championship_submissions', 'championship_submission_player_unique', 'one result exists per finalist');
select has_index('public', 'championship_submissions', 'championship_submission_idempotency_unique', 'submission replay keys are unique');
select has_index('public', 'rematches', 'rematches_pkey', 'one rematch lobby exists per completed room');
select has_function('public', 'submit_championship_result', array['uuid','jsonb','uuid'], 'championship submit RPC exists');
select has_function('public', 'process_expired_championship', array['uuid','uuid'], 'championship timeout RPC exists');
select has_function('public', 'request_rematch', array['uuid','uuid'], 'rematch RPC exists');
select has_function('private', 'complete_match', array['uuid','uuid','championship_resolution_method'], 'authoritative completion operation exists');
select ok((select relrowsecurity from pg_class where oid='public.championship_tiebreakers'::regclass), 'championship rows have RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.championship_tiebreakers'::regclass), 'championship rows force RLS');
select ok((select relrowsecurity from pg_class where oid='public.championship_submissions'::regclass), 'submission rows have RLS');
select ok((select relforcerowsecurity from pg_class where oid='public.match_results'::regclass), 'result rows force RLS');
select ok(not has_table_privilege('authenticated','private.championship_specs','select'), 'clients cannot read championship seeds');
select ok(not has_table_privilege('authenticated','public.championship_submissions','insert'), 'clients cannot bypass result validation');
select ok(not has_table_privilege('authenticated','public.match_results','insert'), 'clients cannot declare a winner');
select ok(not has_table_privilege('authenticated','public.match_results','update'), 'clients cannot rewrite an official result');
select ok(not has_table_privilege('authenticated','public.match_result_players','update'), 'clients cannot rewrite rankings');
select ok(not has_table_privilege('authenticated','public.match_stat_awards','insert'), 'clients cannot invent statistics');
select ok(has_function_privilege('authenticated','public.submit_championship_result(uuid,jsonb,uuid)','execute'), 'authenticated finalists can submit through the RPC');
select ok(not has_function_privilege('anon','public.submit_championship_result(uuid,jsonb,uuid)','execute'), 'unauthenticated callers cannot submit');
select is((select count(*) from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='championship_resolution_method'),4::bigint,'championship methods distinguish skill, timing, timeout, and fallback');
select is((select count(*) from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='match_stat_category'),5::bigint,'exactly five required match statistics are configured');
select ok((select enum_range(null::public.game_phase)::text[] @> array['finalizing','championship_tiebreaker','completed']), 'phase enum models finalizing, championship, and completion');

select * from finish();
rollback;
